name: Rust
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      working-directory: src/
      run: |
          cargo install cargo-web
          rustup target add asmjs-unknown-emscripten
          rustup target add wasm32-unknown-emscripten
          cargo web start
          cargo web start --target-webasm-emscripten=wasm32-unknown-emscripten --release
    - name: Build
      working-directory: src/
      run: cargo build --verbose
    - name: Run tests
      working-directory: src/
      run: cargo test --verbose
    - name: Run
      working-directory: src/
      run: cargo run --verbose