name: Rust
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies      
      run: |
          cargo install cargo-web
          rustup target add asmjs-unknown-emscripten
          rustup target add wasm32-unknown-emscripten          
    - name: Build      
      run: cargo web start