name: Rust
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies      
      run: |
          cargo install cargo-web
          rustup target add asmjs-unknown-emscripten
          rustup target add wasm32-unknown-emscripten
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
    - name: Build
      working-directory: src/
      run: cargo web start
